
Starting up at 12:41:15
Script path: c:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\tr.py
Script directory: c:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script
Tr path: c:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\tr.exe
An error occurred: [Errno 2] No such file or directory: 'c:\\Users\\thasi\\Desktop\\personal shit\\prog\\program\\testing-main\\script\\tr.exe'
Traceback (most recent call last):
  File "c:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\tr.py", line 124, in main
    tr_dest_path = copy_script_to_startup(tr_path, startup_folder)  # Move tr.exe to the startup folder
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\tr.py", line 74, in copy_script_to_startup
    shutil.copy(script_path, destination_path)
  File "C:\Users\thasi\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 419, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\thasi\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\thasi\\Desktop\\personal shit\\prog\\program\\testing-main\\script\\tr.exe'

Starting up at 12:42:22
Script path: C:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\dist\tr.exe
Script directory: C:\Users\thasi\AppData\Local\Temp\_MEI233562
Tr path: C:\Users\thasi\AppData\Local\Temp\_MEI233562\tr.exe
An error occurred: [Errno 2] No such file or directory: 'C:\\Users\\thasi\\AppData\\Local\\Temp\\_MEI233562\\tr.exe'
Traceback (most recent call last):
  File "tr.py", line 124, in main
  File "tr.py", line 74, in copy_script_to_startup
  File "shutil.py", line 419, in copy
  File "shutil.py", line 256, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\thasi\\AppData\\Local\\Temp\\_MEI233562\\tr.exe'

Starting up at 13:18:30
Script path: C:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\dist\tr.exe
Script directory: C:\Users\thasi\AppData\Local\Temp\_MEI73282
Tr path: C:\Users\thasi\AppData\Local\Temp\_MEI73282\tr.exe
An error occurred: [Errno 2] No such file or directory: 'C:\\Users\\thasi\\AppData\\Local\\Temp\\_MEI73282\\tr.exe'
Traceback (most recent call last):
  File "tr.py", line 113, in main
  File "tr.py", line 69, in copy_script_to_startup
  File "shutil.py", line 419, in copy
  File "shutil.py", line 256, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\thasi\\AppData\\Local\\Temp\\_MEI73282\\tr.exe'

Starting up at 13:18:54
Script path: c:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\tr.py
Script directory: c:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script
Tr path: c:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\tr.exe
An error occurred: [Errno 2] No such file or directory: 'c:\\Users\\thasi\\Desktop\\personal shit\\prog\\program\\testing-main\\script\\tr.exe'
Traceback (most recent call last):
  File "c:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\tr.py", line 113, in main
    tr_dest_path = copy_script_to_startup(tr_path, startup_folder)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\tr.py", line 69, in copy_script_to_startup
    shutil.copy(script_path, destination_path)
  File "C:\Users\thasi\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 419, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\thasi\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\thasi\\Desktop\\personal shit\\prog\\program\\testing-main\\script\\tr.exe'

Starting up at 13:22:32
Script path: C:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\dist\tr.exe
Script directory: C:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\dist
Tr path: C:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\dist\tr.exe
Tr moved to: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Cleaner path: C:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\dist\cleaner.exe
An error occurred: [WinError 5] Přístup byl odepřen: 'C:\\Program Files\\CustomCleaner'
Traceback (most recent call last):
  File "tr.py", line 121, in main
  File "tr.py", line 75, in move_cleaner_to_programs
  File "<frozen os>", line 225, in makedirs
PermissionError: [WinError 5] Přístup byl odepřen: 'C:\\Program Files\\CustomCleaner'

Starting up at 13:23:16
Script path: C:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\dist\tr.exe
Script directory: C:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\dist
Tr path: C:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\dist\tr.exe
Tr moved to: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Cleaner path: C:\Users\thasi\Desktop\personal shit\prog\program\testing-main\script\dist\cleaner.exe
Cleaner moved to: C:\Program Files\CustomCleaner\cleaner.exe
